version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/db/
    volumes: 
        - /home/devpc/Projects/FastAPIChallenge/db:/var/lib/postgresql/data/db
    ports:
        - "5432:5432"

volumes:
  postgres:
